name: AmazonGiveaway
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: RubbaBoy <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  webdriver: ^2.1.1
  mysql1: ^0.17.0+1
  args: ^1.5.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
